export const FETCH_ITEMS_START = 'FETCH_ITEMS_START';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAIL = 'FETCH_ITEMS_FAIL';

export const TOGGLE_FAV_SUCCESS = 'TOGGLE_FAV_SUCCESS';
export const TOGGLE_FAV_FAIL = 'TOGGLE_FAV_FAIL';
export const TOGGLE_CHECKBOX = 'TOGGLE_CHECKBOX';
export const ADD_TO_SELECTED = 'ADD_TO_SELECTED';
export const CLEAN_ALL_FILTERS = 'CLEAN_ALL_FILTERS';
